server:
  port: 8089
spring:
  application:
    name: sys
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?charset=utf8mb4&useSSL=false
    username: root
    password: 123456
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 100
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: com.lt.sys.configuration.MySQL5InnoDBDialectUtf8mb4
        hbm2ddl:
          auto: update
  profiles:
    active: dev